## Loading in dataframes from Files

differnt type of file formates based on size 
* parquet
* feather
* xlsx
* csv
* json

In [9]:
import pandas as pd

In [10]:
coffee = pd.read_csv('test_data/coffee.csv')
coffee.to_parquet

<bound method DataFrame.to_parquet of           Day  Coffee Type   Units Sold
0      Monday     Espresso           25
1      Monday        Latte           15
2     Tuesday     Espresso           30
3     Tuesday        Latte           20
4   Wednesday     Espresso           35
5   Wednesday        Latte           25
6    Thursday     Espresso           40
7    Thursday        Latte           30
8      Friday     Espresso           45
9      Friday        Latte           35
10   Saturday     Espresso           45
11   Saturday        Latte           35
12     Sunday     Espresso           45
13     Sunday        Latte           35>

In [11]:
coffee

          Day  Coffee Type   Units Sold
0      Monday     Espresso           25
1      Monday        Latte           15
2     Tuesday     Espresso           30
3     Tuesday        Latte           20
4   Wednesday     Espresso           35
5   Wednesday        Latte           25
6    Thursday     Espresso           40
7    Thursday        Latte           30
8      Friday     Espresso           45
9      Friday        Latte           35
10   Saturday     Espresso           45
11   Saturday        Latte           35
12     Sunday     Espresso           45
13     Sunday        Latte           35

In [12]:
coffee.head()

         Day  Coffee Type   Units Sold
0     Monday     Espresso           25
1     Monday        Latte           15
2    Tuesday     Espresso           30
3    Tuesday        Latte           20
4  Wednesday     Espresso           35

In [13]:
coffee.tail()

         Day  Coffee Type   Units Sold
9     Friday        Latte           35
10  Saturday     Espresso           45
11  Saturday        Latte           35
12    Sunday     Espresso           45
13    Sunday        Latte           35

In [14]:
coffee.sample(5)

         Day  Coffee Type   Units Sold
11  Saturday        Latte           35
10  Saturday     Espresso           45
9     Friday        Latte           35
6   Thursday     Espresso           40
7   Thursday        Latte           30

### Accessing Data with Pandas

In [15]:
coffee.loc[[0,1,5]]

         Day  Coffee Type   Units Sold
0     Monday     Espresso           25
1     Monday        Latte           15
5  Wednesday        Latte           25

In [16]:
# coffee.loc[5:10, ["Day","Units Sold"]]