* NaN (Not a Number)
* None (for object data type)

* isnull()
* true - NaN is present
* False - value is present

In [18]:
import pandas as pd

In [19]:
data = {
    "Name": ['Ram', None, 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28,34,None,30,29,40,25,None],
    "Salary": [50000,60000,45000,52000,49000, 70000,48000,None],
    "Performance Score": [None,90,78,92,88,95,80,89]
}

df = pd.DataFrame(data)

In [20]:
print(df.isnull(), "\n")
print(df.isnull().sum())

    Name    Age  Salary  Performance Score
0  False  False   False               True
1   True  False   False              False
2  False   True   False              False
3  False  False   False              False
4  False  False   False              False
5  False  False   False              False
6  False  False   False              False
7  False   True    True              False

Name                 1
Age                  2
Salary               1
Performance Score    1
dtype: int64

* drope the whole row from the table by using dropna()  

* axis = 0 (drop the rows where Null is present)
* axis = 1 (drop the coloum where Null is present)

In [21]:
df.dropna(axis=0, inplace=False)

        Name   Age   Salary  Performance Score
3  Dhanshyam  30.0  52000.0               92.0
4      Aditi  29.0  49000.0               88.0
5    Jagdish  40.0  70000.0               95.0
6        Raj  25.0  48000.0               80.0

In [22]:
df.dropna(axis=1, inplace=False)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7]

* replace the value with any other thing like mean 0 max  
* fillna()

In [23]:
df.fillna(0, inplace=False)

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                0.0
1          0  34.0  60000.0               90.0
2  Ghanshyam   0.0  45000.0               78.0
3  Dhanshyam  30.0  52000.0               92.0
4      Aditi  29.0  49000.0               88.0
5    Jagdish  40.0  70000.0               95.0
6        Raj  25.0  48000.0               80.0
7     Simran   0.0      0.0               89.0

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=False) 

df['Salary'].fillna(df['Salary'].mean(), inplace=False)

0    50000.000000
1    60000.000000
2    45000.000000
3    52000.000000
4    49000.000000
5    70000.000000
6    48000.000000
7    53428.571429
Name: Salary, dtype: float64

### Interpolation
It is the mathematical process of estimating unknown values that fall between known data points

* interpolate() 
#### Key Methods
* linear
* time
* polynomial
* nearest

#### Parameters
* axis = fill missing values along columns (axis=0) or across rows (axis=1)
* limit = Sets a maximum number of consecutive NaNs that can be filled in one go
* limit_direction = Determines the direction of the filling ('forward', 'backward', or 'both')
* inplace = True or False

In [30]:
data = {
    "Name": ['Ram', 'Palak', 'Ghanshyam', 'Dhanshyam', 'Aditi', 'Jagdish', 'Raj', 'Simran'],
    "Age": [28,34,None,30,29,40,25,None],
    "Salary": [50000,60000,45000,52000,49000, 70000,48000,None],
    "Performance Score": [None,90,78,92,88,95,80,89]
}

df = pd.DataFrame(data)

In [33]:
df.interpolate(axis=0, inplace=False)

C:\Users\NISHIT JAIN\AppData\Local\Temp\ipykernel_18096\1121019559.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(axis=0, inplace=False)

        Name   Age   Salary  Performance Score
0        Ram  28.0  50000.0                NaN
1      Palak  34.0  60000.0               90.0
2  Ghanshyam  32.0  45000.0               78.0
3  Dhanshyam  30.0  52000.0               92.0
4      Aditi  29.0  49000.0               88.0
5    Jagdish  40.0  70000.0               95.0
6        Raj  25.0  48000.0               80.0
7     Simran  25.0  48000.0               89.0

#### Linear

In [34]:
data = {
"Time": [1,2,3,4,5],
"Value": [10, None, 30, None, 50]
}

df = pd.DataFrame(data)
print(df)

   Time  Value
0     1   10.0
1     2    NaN
2     3   30.0
3     4    NaN
4     5   50.0

In [39]:
df['Value'] = df['Value'].interpolate(method='linear')
print(df)

   Time  Value
0     1   10.0
1     2   20.0
2     3   30.0
3     4   40.0
4     5   50.0