* sorting data
* SORTING DATA 1 COLUMN sort_values()
* df.sort_values(by="Column Name", ascending = True/False, inplace = True)

In [1]:
import pandas as pd

In [7]:
data = {
    "Name": ['Arun', 'Varun', 'Karun'],
    "Age": [23,54,12],
    "Salary": [10000, 20000,30000]
    }

df = pd.DataFrame(data)

In [8]:
df.sort_values(by='Age', ascending=False, inplace=False )

    Name  Age  Salary
1  Varun   54   20000
0   Arun   23   10000
2  Karun   12   30000

In [9]:
df.sort_values(by='Age', ascending=True, inplace=False )

    Name  Age  Salary
2  Karun   12   30000
0   Arun   23   10000
1  Varun   54   20000

In [10]:
df.sort_values(by=['Age', 'Salary'], ascending=False, inplace=False )

    Name  Age  Salary
1  Varun   54   20000
0   Arun   23   10000
2  Karun   12   30000